### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by entwanne** [entwanne/cours_python_avance#19]
- [ ] Ajouter paragraphe redéfinition d'une signature de fonction avec l'attribut `__signature__`
- [ ] renommer `(cls, name, bases, dict)` des métaclasses en `(cls, name, bases, namespace)`
- [ ] `__prepare__` keyword arguments
- [ ] « En fait, `@` ne doit pas nécessairement être suivi d’un nom d’objet, des arguments peuvent aussi s’y ajouter à l’aide de parenthèses » → Préciser que depuis Python 3.9, toute expression est valide derrière le `@` (<https://zestedesavoir.com/tutoriels/954/notions-de-python-avancees/2-functions/3-decorators/#2-2-parameterize>)
- [ ] Arguments uniquement nommés (`*`) et arguments uniquement positionnels (`/`)
